// Generated by CoffeeScript 1.9.3
(function() {
  var cp, files, fs;

  fs = require('fs');

  cp = require('child_process');

  files = fs.readdirSync('./dist');

  files.forEach(function(file) {
    var str;
    if (/html$/.exec(file)) {
      str = fs.readFileSync('./dist/' + file).toString();
      str = str.replace(/src=("|')([^<][^'"]*)("|')/g, function(str, _, capture) {
        var path;
        if (!/^http/.exec(capture)) {
          path = 'site/' + capture.replace('./', '').replace('imgs/', '');
          return 'src="<%= image_path("' + path + '") %>"';
        } else {
          return str;
        }
      });
      str = str.replace(/<!-- BEGINCSS -->(.|\n)*<!-- ENDCSS -->/, '<%= stylesheet_link_tag "portal" %><link rel="icon" href="/favicon.png?v=6" />');
      str = str.replace(/<!-- PRODONLY/g, '').replace(/END -->/g, '');
      str = str.replace(/<!-- TESTONLY(.|\n)*?ENDTESTONLY -->/g, '');
      return fs.writeFileSync('./dist-rails/' + file + '.erb', str);
    }
  });

  files = fs.readdirSync('./src/sass');

  files.forEach(function(file) {
    var str;
    if (/sass$/.exec(file)) {
      str = fs.readFileSync('./src/sass/' + file).toString();
      str = str.replace(/[^-]url\("(.*)"\)/g, function(str, capture) {
        var path;
        if (/fonts/.exec(capture)) {
          path = capture.replace('../', '').replace('fonts/', '');
          return ' url(font-path("' + path + '"))';
        } else {
          if (/^http/.exec(capture)) {
            return str;
          } else {
            path = capture.replace('[^\.]\./', '').replace('\.\./', '').replace('imgs/', '');
            return ' image-url("site/' + path + '")';
          }
        }
      });
      return fs.writeFileSync('./dist-rails/sass/' + file, str);
    }
  });

  fs.readdirSync('./dist-rails').forEach(function(file) {
    if (/html/.exec(file)) {
      return cp.exec('cp ./dist-rails/' + file + ' /Users/KspR/Dev/whibo/app/views/site/' + file);
    }
  });

  fs.readdirSync('./dist-rails/sass').forEach(function(file) {
    if (/sass/.exec(file)) {
      return cp.exec('cp ./dist-rails/sass/' + file + ' /Users/KspR/Dev/whibo/app/assets/stylesheets/portal/' + file);
    }
  });

}).call(this);
